### ISSUE TITLE
New TfL API

### ISSUE THREAD

**Issue by jpsingleton** [OliPicard/tubey.py#2]
TfL have a new secure version of their API which returns the status as JSON with CORS headers: 
https://api.tfl.gov.uk/line/mode/tube,overground,dlr/status

You can read it easily with some python like this:

``` python
import urllib
import json

response = urllib.urlopen('https://api.tfl.gov.uk/line/mode/tube,overground,dlr/status')
data = json.load(response)

for line in data:
    print "{}:".format(line['name'])
    for status in line['lineStatuses']:
        print "    {}".format(status['statusSeverityDescription'])
        if status['statusSeverity'] != 10: # https://api.tfl.gov.uk/line/meta/severity
            print "        {}".format(status['reason'])
    print "\n"
```

You can include other forms of transport too: 
https://api.tfl.gov.uk/line/mode/tube,overground,dlr,tram,national-rail,cable-car,river-bus,river-tour/status

I've [previously used](https://github.com/jpsingleton/London-Tube-Status/blob/master/index.php#L39) the old XML API (with PHP and XSLTs) and was going to [integrate it into Huxley](https://github.com/jpsingleton/Huxley/issues/7) (transforming it into cross domain JSON) before I discovered how to get the same data from the new API.

**Comment by jpsingleton** [comment]
Produces this output when nothing is disrupted:

```
Bakerloo:
    Good Service

Central:
    Good Service

Circle:
    Good Service

District:
    Good Service

DLR:
    Good Service

Hammersmith & City:
    Good Service

Jubilee:
    Good Service

London Overground:
    Good Service

Metropolitan:
    Good Service

Northern:
    Good Service

Piccadilly:
    Good Service

Victoria:
    Good Service

Waterloo & City:
    Good Service

```

**Comment by OliPicard** [comment]
Hi James,

Many thanks for alerting me to this!

I was unaware of the new JSON api, I'll look into getting this implimented in a new client in the future.

Thanks again for looking into this, Seems very promising!

**Comment by jpsingleton** [comment]
No problem. Here's a bigger example:
- https://github.com/Blinkinlabs/BlinkyTape_Python/blob/master/London_Underground_Status.py

Thanks for the Huxley wiki Azure updates.

**Comment by OliPicard** [comment]
Hey James,

Was a pleasure helping to write the azure guide. I'll attempt to rewrite it in the future for clarify sake. I'll look at the blinkytape implementation. Looks promising!
